= Spreadsheet To Database via POI and JPA

This is a rough outline of a quick hack to read a spreadsheet using Apache POI
and write it into a database using the Java Persistence Architecture (JPA).

There is a lot of code that is specific to our particular spreadsheet and database.
Please *do not expect this either to compile or work as it stands*.

The _persistence.xml_ file is omitted as it contains my database password and other info.
There is instead a _sample-persistence.xml_ for you to copy to persistence.xml and edit.
Assuming you use the best database (PostgreSQL) you only have to change the JDBC URL,
the usename, and the password. If you use a lesser database you will have to change the
POM file as well.

Also, the JPA entity class isn't included as it's in a dependant project, but
the Member class is pretty obvious, and you probably already have one like it if
you're needing to convert a spreadsheet into it.

----
@Entity public class Member {
	@Id long id;
	String firstName, lastName;
	...other fields you need...
}
----
Use your IDE or https://projectlombok.org/[Lombok] to generate accessors,
and you should be operational.
